[profile.default]
    auto_detect_remappings = false
    bytecode_hash = "none" # Get reproducible bytecode across machines by removing metadata hash from runtime bytecode
    solc_version = "0.8.23"
    evm_version = "paris" # Prevent PUSH0 incompatibility with other EVM chains
    fuzz = { runs = 256 }
    gas_reports = ["*"]
    libs = ["lib"]
    optimizer = true
    optimizer_runs = 9_999_999 # Etherscan max is 100 million
    out = "out"
    script = "script"
    src = "src"
    test = "test"
    via_ir = false # Disable ir optimizer, minimal gas savings not worth the potential for bugs

[profile.ci]
    fuzz = { runs = 10_000 }
    verbosity = 4

[fmt]
    line_length = 120
    wrap_comments = true