name: Forge Tests

env:
  FOUNDRY_PROFILE: "ci"

on: [push, pull_request]

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
      
      - name: Yarn Install and Build
        run: |
          cd lib/LayerZero-v2
          yarn
          yarn build

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: pnpm Install and Build
        run: |
          cd lib/devtools
          pnpm install --reporter=append-only

      - name: Check formatting
        run: forge fmt --check

      - name: Run forge tests
        # env:
        #   ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        # run: forge test --fork-url "https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_API_KEY"
        run: forge test --ffi -vvv